  spring:
    application:
      name: WorkSystem
    datasource:
      url: jdbc:mysql://localhost:3306/worksystem
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    port: 8080

  # application.yml
  mybatis-plus:
    mapper-locations: classpath*:mapper/**/*.xml
    type-aliases-package: com.worksystem.entity
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启 SQL 日志

  logging:
    level:
      com.WorkSystem: debug




